name: Build and Deploy to Azure App Service (Advanced)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: sentiment-analysis-ryan-20241215-ezgkezdjfsdpf8by
  AZURE_RESOURCE_GROUP: rg-sentimentanalyzer-proj1-dev-001
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore SentimentAnalysis.csproj
      
    - name: Build
      run: dotnet build SentimentAnalysis.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test SentimentAnalysis.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
      
    - name: Publish
      run: dotnet publish SentimentAnalysis.csproj --configuration Release --no-build --output ./publish
      
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: ./publish
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: ./publish
