name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore SentimentAnalysis.csproj
      
    - name: Build
      run: dotnet build SentimentAnalysis.csproj --configuration Release --no-restore
      
    - name: Publish for Linux
      run: dotnet publish SentimentAnalysis.csproj --configuration Release --no-build --output ./publish --runtime linux-x64 --self-contained false
      
    - name: Clean up publish folder
      run: |
        # Remove any nested publish folders
        find ./publish -name "publish" -type d -exec rm -rf {} + 2>/dev/null || true
        # Remove Windows-specific files
        find ./publish -name "*.exe" -delete
        find ./publish -name "*.pdb" -delete
        # Ensure proper file permissions
        chmod +x ./publish/SentimentAnalysis.dll || true
      
    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B024A65E78C946CEB5489E3211048635 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9C7931D652AA42A2854B4D283E358777 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CC0010FCFC2E40B898662F97EE85FB15 }}
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: sentiment-analysis-ryan-20241215
        package: ./publish